### ISSUE TITLE
New user of notification-server

### ISSUE THREAD

**Issue by QuickSander** [Supereg/homebridge-http-notification-server#4]
Hi,

With respect to "please contact me if you want to be added here":

https://github.com/QuickSander/homebridge-better-http-rgb#switch-status-object

This is a RGB light device __fork__ with added HTTP notification server support. I hope you can add it to the list of projects using your excellent http-notification-server.

Next I would like to fork your humidity or temperature project to create a ambient light sensor if you allow.

**Comment by bauer-andreas** [comment]
Thanks for the interest. I added you to the list.
Regarding the README. Is it on purpose that the only characteristic, which can be updated via homebridge-http-notifiaction-server is the `On` characteristic. Also, I didn't quite understand the part explaining "using the specified `notificationID` as `service`" since the `service` property of the request is not used in your code (obviously, since your device only exposes one service).

Regarding the forks, both projects are licensed under ISC so do what you want as long as you include the license in all copies, see [LICENSE](https://github.com/Supereg/homebridge-http-humidity-sensor/blob/master/LICENSE).

**Comment by QuickSander** [comment]
Thanks for the rectifications. I scraped the part mentioning the `service` as this was indeed clearly wrong since I intend to only expose the `On` service. For now my intention is only to expose he `On` service as I personally think other services for a light (colour) could be neat to push, but do not add much to the overall user experience.

I will respect the license (and original author of the project).
