### ISSUE TITLE
Unexpected end of JSON Input

### ISSUE THREAD

**Issue by tanami20** [Supereg/homebridge-http-notification-server#9]
Hi,

I am getting this in the logs: **[18/04/2021, 10:59:32 am] [notification-server] 'tenant-Light' sent malformed body: Unexpected end of JSON input**

Testing with Postman I am sending 

http://192.168.18.203:8085/tenant-EveLight?characteristic=on&value=true&password=supersecret

as a POST in Postman. And it just comes back as Bad Request. 

Any ideas?

**Comment by bauer-andreas** [comment]
The values what you are currently placing in the query part of the url (like `value`, `characteristics`) should be placed in the **body** (formatted as json, as shown in the README) of the POST request.

The server is trying to read the data from the http body in order to parse the request. And as you (seemingly) don't pass anything in the body it fails with "unexpected end of json input" (meaning it expected some data but there was not data).

**Comment by tanami20** [comment]
Perfect, sorry for the Noob question! Working now.
